version: '3'

services:
  pw-front:
    build:
      context: ./pw-front-svelte
    environment: # warning: for build environment, use .env.docker in ./pw-front-svelte/
      - PUBLIC_SERVER_URL=http://45.132.244.146:3030/ # todo: automatically get server url
      - PUBLIC_PALDEX_URL=http://45.132.244.146:3080/ # todo: automatically get server url
    ports:
      - "3020:3000"

  pw-back:
    build:
      context: ./pw-back
    environment:
      - PORT=3030  # Set the desired port for pw-back
      - ROOT_DIR='/home/xiq/srv/palworld'
      - PAL_DIR='/home/xiq/srv/palworld/game/Pal'
      - SERVER_ID='0'
      - WORLD_GUID='F37D14B248EFAFC63FB56E8E65671166'
      - PYTHON_RUNTIME='python3'
    ports:
      - "3030:3030"

  palworld-paldex-api:
    build:
      context: https://github.com/mlg404/palworld-paldex-api.git#v1.2.0
      dockerfile: Dockerfile
    ports:
      - "3080:3000"  # Change the host port to the desired port