version: '3'

services:
  pw-front:
    build:
      context: ./pw-front-svelte
      args:
      - PUBLIC_SERVER_URL=<server-url>:3030/ # todo: automatically get server url
      - PUBLIC_PALDEX_API_URL=<server-url>:3080/ # todo: automatically get server url      
    environment: # warning: for build environment, use .env.docker in ./pw-front-svelte/
      - PUBLIC_SERVER_URL=<server-url>:3030/ # todo: automatically get server url
      - PUBLIC_PALDEX_API_URL=<server-url>:3080/ # todo: automatically get server url
    ports:
      - "3020:3000"

  pw-back:
    build:
      context: ./pw-back
    environment:
      - PORT=3030
      - ROOT_DIR=/home/srv/palworld
      - PAL_DIR=/home/srv/palworld/game/Pal
      - SERVER_ID=0
      - WORLD_GUID=F37D14B248EFAFC63FB56E8E65671166
      - PYTHON_RUNTIME=python3
    volumes:
      - /home/xiq/srv/palworld:/home/srv/palworld
    ports:
      - "3030:3030"

  palworld-paldex-api:
    build:
      context: https://github.com/mlg404/palworld-paldex-api.git#v1.3.0
      dockerfile: Dockerfile
    ports:
      - "3080:3000"  # Change the host port to the desired port